### ISSUE TITLE
Date transformers casting dtypes if passed in as an input

### ISSUE THREAD

**Issue by Decima2014** [lvgig/tubular#142]
We have had some issues in the past with some tubular date transformers requiring conflicting specific dtypes to be accepted by the transformer, ie: datetime.object, datetime.date, datetime[n64].

The ExtractTimeInfo and DateDifferenceTransformer for example requiring different dtypes

I believe having an option to automatically cast the column to the required dtype as opposed to directly failing would be preferable

**Comment by Decima2014** [comment]
You sometimes dont want your datetime columns to be casted to a new type even if that type is what the transformer requires, so your dates transformers could use a temporary copy of the column for the transformation

**Comment by TommyMatthews** [comment]
Will look at this this sprint

**Comment by TommyMatthews** [comment]
DateDiffLeapYearTransformer also raises an error incorrectly when passed a datetime object

**Comment by TommyMatthews** [comment]
I've characterised the problem slightly more. Considering the two main datetime datatypes, datetime.date and datetime.datetime:

- DateTimeInfoExtractor: only works on datetime.datetime due to how it's written - needs the .dt accessor only available to datetime.datetime objects. I think this unavoidably needs temporary casting inside transform for full consistency across dates.py

- DateDifferenceTransformer: works with either datetime.datetime or datetime.time, but can't handle the combination of the two types across the two columns. Think this should be a quick fix.

- DateDifferenceLeapYearTransformer: no issues once I fix the input checks.
