### ISSUE TITLE
Handling of np.nan in test asserts

### ISSUE THREAD

**Issue by limlam96** [lvgig/tubular#233]
What?
Dandan raised Q of whether == checks are safe for np.NaN, which occurs in our tests [e.g.](https://github.com/lvgig/tubular/blob/901b29d25e0ed4a0abcdb2d60945aec16112ea82/tests/capping/test_OutOfRangeNullTransformer.py#L161), investigate whether we need to improve handling here

Why?
Ensure test behaviour is as expected

**Comment by davidhopkinson26** [comment]
had a little bit of a play with the linked example:

```
>>> import numpy as np
>>> np.nan == np.nan
False
```
np.nan != np.nan.  In fact a recommended test for if something is np.nan is to  [check x != x](https://stackoverflow.com/questions/944700/how-to-check-for-nan-values)
```
>>> {"a": [np.nan, np.nan], "b": [None, np.nan], "c": [np.nan, None]} == {"a": [np.nan, np.nan], "b": [None, np.nan], "c": [np.nan, None]}
True
>>> {"a": [np.nan, np.nan], "b": [None, np.nan], "c": [np.nan, None]} == {"a": [np.nan, np.nan], "b": [None, np.nan], "c": [None, None]}
False
>>> {"a": [np.nan, np.nan], "b": [None, np.nan], "c": np.nan} == {"a": [np.nan, np.nan], "b": [None, np.nan], "c": np.nan}
True`
```
comparing dictionaries containing np.nan as values, or as elements in list values does appear to work as expected.

Would appear that this is indeed safe used as it is in the example.

**Comment by adamsardar** [comment]
Is the question whether `__eq__` is safe for dicts that contain `np.nan`? Dave shows that it's ok (phew).

But the general question of testing for `np.nan` - we should use `np.isnan` rather than an equality match?

**Comment by davidhopkinson26** [comment]
I guess that using {}.__eq__ without any documentation promising that behaviour risks a change being implemented which could break tests.  It does not however seem likely to me that this behaviour would be removed, cant imagine it isn't intentional!

Would maybe be more concerned if we had tests which might start to pass when they shouldn't (i.e. silent errors) but the change would cause some of our tests to start failing and would be fairly obvious from the traceback that the dict comparison isn't working.   Personally I feel comfortable leaving this alone now and closing the issue.

**Comment by adamsardar** [comment]
I feel comfortable closing this too.
