### ISSUE TITLE
Double check test inheritances

### ISSUE THREAD

**Issue by limlam96** [lvgig/tubular#255]
What?

Spotted that tests from [test_BaseMappingTransformerMixin.py](https://github.com/lvgig/tubular/blob/main/tests/mapping/test_BaseMappingTransformMixin.py) are not imported anywhere, would expect that these would be inherited by relevant test classes in mixin-like way so that these classes also inherit all test cases.

There is this comment at the top of the file:
'# Note there are no tests that need inheriting from this file as the only difference is an expected transform output'

So it may be that the test cases are already covered and this is not a bug, but think I would still lean towards refactoring to have tests mirror mixin structure.

Task is to investigate this and make any changes necessary. If this is not a bug, we can proceed with a release and think about refactoring at later date.

Related follow up task will be to double check other test inheritances to ensure that other classes have correct test suite.

Why?

Ensure tests are being run as expected

How?

Start by investigating testing setup for MappingTransformer to investigate if BaseMappingTransformerMixin functionality is covered. 

After resolving MappingTransformer, would do a quick scan of other files to check for similar missed mixin issues.

**Comment by davidhopkinson26** [comment]
This is intentional.  The tests here are intended for specifically unit testing the mixin methods and were not intended to be inherited in other test classes.  

- `test_expected_outputs` is specific to this method and not suitable to inherit so fine as is. The sole thing this mixin does is apply mappings using pd.Dataframe.replace() so this is really the only test needed here. (suggestions for other tests welcome!)
- `test_mappings_unchanged` is also tested in test_BaseMappingTransformer.BaseMappingTransformerTransformTests so is already inherited by child classes in this module through there. Could inherit .BaseMappingTransformerTransformTests here to delete from this test module.
- Several tests have been duplicated exactly from GenericTransformTests but with the transformer declared using  x = `BaseMappingTransformMixin(columns=["a"]) `rather than` x = initialized_transformers[self.transformer_name] `.  Since BaseMappingTransformerMixin is in the minimal_attribute_dict i believe these test could simply be deleted as they are redundant.

All in all no changes required as far as I can tell so this shouldn't stop a release.  

Weirdness all comes from having both BaseMappingTransformer and BaseMappingTransformerMixin classes which is quite confusing and should probably be a target for future refactors.
